### ISSUE TITLE
Allow custom messages

### ISSUE THREAD

**Issue by tomekwi** [maxogden/tape-spawn#4]
Hi,

how about allowing an optional custom message in `st.fails()`, `st.succeeds()`, `st.exitCode()`, etc.? Just like *tape* allows them in every type of assertion – including simple ones like [`t.pass()`](https://github.com/substack/tape/tree/b235fce183f0e95b3e55ee32ae193c4b232c09f6#tpassmsg).

**Comment by maxogden** [comment]
+1, some of the methods take a message as the last argument but would be nice if all of them did
